"""add ondelete='cascade'

Revision ID: 12b88353d6ea
Revises: b74b0488d2a2
Create Date: 2024-11-23 00:55:57.946267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b88353d6ea'
down_revision: Union[str, None] = 'b74b0488d2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('place_reaction_place_id_fkey', 'place_reaction', type_='foreignkey')
    op.drop_constraint('place_reaction_user_id_fkey', 'place_reaction', type_='foreignkey')
    op.create_foreign_key(None, 'place_reaction', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'place_reaction', 'place', ['place_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place_reaction', type_='foreignkey')
    op.drop_constraint(None, 'place_reaction', type_='foreignkey')
    op.create_foreign_key('place_reaction_user_id_fkey', 'place_reaction', 'user', ['user_id'], ['id'])
    op.create_foreign_key('place_reaction_place_id_fkey', 'place_reaction', 'place', ['place_id'], ['id'])
    # ### end Alembic commands ###
