"""add place_image and place_type

Revision ID: 24f2412c8447
Revises: 12b88353d6ea
Create Date: 2024-11-23 02:19:56.032559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f2412c8447'
down_revision: Union[str, None] = '12b88353d6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_image',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'image_url')
    )
    op.create_table('place_type',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'type')
    )
    op.add_column('place', sa.Column('name', sa.String(), nullable=False))
    op.add_column('place', sa.Column('rating', sa.DECIMAL(precision=2, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'rating')
    op.drop_column('place', 'name')
    op.drop_table('place_type')
    op.drop_table('place_image')
    # ### end Alembic commands ###
