"""improve rating accuracy

Revision ID: 3d078fc06fdd
Revises: 3fecb0578b38
Create Date: 2024-11-23 02:50:46.142492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d078fc06fdd'
down_revision: Union[str, None] = '3fecb0578b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'rating',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
