"""add place and place_reaction tables

Revision ID: b74b0488d2a2
Revises: c30b5306e2db
Create Date: 2024-11-21 18:34:47.306068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74b0488d2a2'
down_revision: Union[str, None] = 'c30b5306e2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=9), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=9), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_reaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reaction IN ('like', 'dislike')", name='reaction_check'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_reaction')
    op.drop_table('place')
    # ### end Alembic commands ###
